### ISSUE TITLE
Kiedy będzie oficjalny release?

### ISSUE THREAD

**Issue by Xmonpl** [xDroni/TeamSpeak3-Bot#1]
Witam!

Chciałbym się dowiedzieć kiedy będzie oficjalny release music bota oraz czy będzie wspierał spotify?

 Pozdrawiam.

**Comment by xDroni** [comment]
Ze Spotify jest ten problem, że jego API (jeszcze) nie wspiera dodawania piosenek do kolejki. Będę starał się to rozwiązać innym sposobem, jak na razie piosenki ze Spotify można puszczać pojedynczo, tj. wpisana na TeamSpeak piosenka jest puszczana natychmiast.
Jeżeli bardziej zależy Ci na kolejkowaniu piosenek, to zawsze możesz korzystać z YouTube (z nim nie ma problemów).
Długo zbierałem się do wydania oficjalnego release, po Twojej prośbie chyba wezmę się za to na poważnie :D

**Comment by Xmonpl** [comment]
Dobrze, czekam z niecierpliwoscia, kiedy wydasz pierwsza działająca betę ☺ Mam nadzieje, że stanie się to w najbliższym czasie. Na moim teamspeaku na pewno będziemy używać twoich music botów!

**Comment by xDroni** [comment]
Lżejsza, szybsza wersja bota, przepisana na Node JS:
https://github.com/xDroni/TeamSpeak-3-Music-Bot-Node-JS

Jest tam też kilka fajnych funkcji poza tymi muzycznymi. Nie zrobiłem jeszcze instrukcji instalacji bota, ale pomogę jest będzie taka potrzeba.

**Comment by Xmonpl** [comment]
Podczas użycia polecenia 'npm install' wypluwa mi taki błąd: https://xmon.cf/priv-dl/2019-08-28T11_05_32_166Z-debug.log nie wiem czy to z winy mojego serwera czy mojego braku doświadczenia z aplikacjami napisanymi w node'ie.

**Comment by xDroni** [comment]
Zaktualizuj npm, używasz starej wersji. Moja wersja NodeJS to 10.16.0, npm to 6.9.0
Zainstaluj sobie na serwerze ffmpeg jeśli nie masz, potrzebny jest do modułu youtube-audio-stream. Jak to nie przyniesie efektów to będziemy się głowić dalej, na razie otwórz issue w tamtym repozytorium bo temat nie dotyczy tego.

**Comment by Xmonpl** [comment]
okej, spróbuje zaktualizować :D
